# Generated by Django 4.1.2 on 2023-01-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='I prefer not to say', max_length=200),
        ),
    ]
