# Generated by Django 4.1.2 on 2022-12-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_payment_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=250)),
                ('mode', models.CharField(max_length=50)),
                ('amount', models.PositiveBigIntegerField()),
                ('payment_for', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=250)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
