# Generated by Django 4.1.2 on 2023-01-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_applicant_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('none', 'none')], default='None', max_length=200),
        ),
    ]
