# Generated by Django 4.1.2 on 2022-12-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paymentstatement_tenantfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentstatement',
            old_name='mode',
            new_name='mode_of_payment',
        ),
    ]
