# Generated by Django 4.1.2 on 2022-12-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_mode_paymentstatement_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantfeedback',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
