# Generated by Django 4.1.2 on 2023-01-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentStatement',
        ),
        migrations.DeleteModel(
            name='TenantFeedback',
        ),
    ]
